;; Automatically generated by private/make-aliased-libraries.sps
#!r6rs
(library (srfi :38)
  (export
    read-with-shared-structure
    read/ss
    write-with-shared-structure
    write/ss)
  (import (srfi :38 with-shared-structure))
)
