<Project>
  <Target Name="unfuck" BeforeTargets="BeforeBuild" Condition="Exists('$(MSBuildThisFileDirectory)../contentFiles/any/any/nuget.sls')">
    <Warning Code="UNFUCK" Text="Ironscheme needs unfucking for real $(MSBuildThisFileDirectory)" />

    <Delete Files="$(MSBuildThisFileDirectory)../contentFiles/any/any/nuget.sls" />
  </Target>
</Project>