<Project>
  <Target Name="unfuck" BeforeTargets="BeforeBuild">
    <Warning Code="UNFUCK" Text="Ironscheme needs unfucking for real $(MSBuildProjectDirectory)" />
    <Unzip SourceFiles="$(MSBuildThisFileDirectory)libs.zip" DestinationFolder="$(MSBuildProjectDirectory)/lib/" />

    <ItemGroup>
      <Content CopyToOutputDirectory="Always" CopyToPublishDirectory="Always" Include="lib/**/*.*" />
    </ItemGroup>
  </Target>
</Project>