version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: IronScheme\IronScheme\Properties\AssemblyInfo.cs
  assembly_version: '1.0.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(SHA)'environment:
  matrix:
  - FX_VERSION: v2.0
#  - FX_VERSION: v4.0install:
- cmd: >-
    set SHA=%APPVEYOR_REPO_COMMIT:~0,7%
    
    set QUIET=1

    cinst ilmerge

    cinst zip

    curl -o xz.zip http://tukaani.org/xz/xz-5.2.1-windows.zip

    unzip -o xz.zip -d xz bin_i686-sse2/xz.exe

    copy xz\bin_i686-sse2\xz.exe "C:\Program Files\Git\usr\bin\"

    set PATH=%PATH%;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;%APPVEYOR_BUILD_FOLDER%\IronScheme\tools\;
build_script:
- cmd: msbuild "IronScheme\IronSchemeCore.sln" /v:m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:TargetFrameworkVersion=%FX_VERSION% /p:Configuration=Release
test_script:
- cmd: >-
    cd IronScheme\IronScheme.Console\bin\Release

    rem these have to be in order

    rem nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Debug
    
    rem nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Release

    rem nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Conformance

    rem nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.SRFI

    rem nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Other

    rem nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Teardown

    cd %APPVEYOR_BUILD_FOLDER%

    if "%FX_VERSION%" EQU "v2.0" call ci-artefact.cmd
artifacts:
- path: IronScheme-*.zip
- path: IronScheme-*.tar.xz
before_deploy:
- cmd: >-
    rem precompile libraries for Nuget

    echo (compile-system-libraries) | install-stage\IronScheme\IronScheme.Console32-v2.exe

    cd install-stage

    rem prep nuget packages ... WIP
