version: 1.0.{build}
skip_tags: true
image: Visual Studio 2022
branches:
  only:
  - master
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: IronScheme\IronScheme\Properties\AssemblyInfo.cs
  assembly_version: '1.0.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(SHA)'
install:
- cmd: |
    cd %APPVEYOR_BUILD_FOLDER%
    git submodule update --init --recursive
    set SHA=%APPVEYOR_REPO_COMMIT:~0,7%
    set QUIET=1
    choco install ilmerge
    set PATH=%PATH%;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\;%APPVEYOR_BUILD_FOLDER%\IronScheme\tools\;
    choco install dotnet-9.0-sdk --pre -y
    dotnet --info
nuget:
  project_feed: true
build_script:
- cmd: |
    dotnet restore "IronScheme\IronSchemeCore.sln"
    type "IronScheme\TailCallMaker\obj\project.assets.json"
    echo 1 > IronScheme\IronScheme\Compiler\numberlexer.lex.cs
    echo 1 > IronScheme\IronScheme\Compiler\ironscheme.lex.cs
    echo 1 > IronScheme\IronScheme\Compiler\NumberParser.y.cs
    echo 1 > IronScheme\IronScheme\Compiler\IronScheme.y.cs
    dotnet msbuild "IronScheme\IronSchemeCore.sln" /v:m /logger:"C:\Program Files\AppVeyor\BuildAgent\dotnetcore\Appveyor.MSBuildLogger.dll" /p:Configuration=Release /p:UseNetFxIlTools=False
test_script:
- cmd: |
    cd IronScheme\IronScheme.Console\bin\Release\net20
    rem these have to be in order
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Debug
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Release
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Conformance
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.SRFI
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Other
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Teardown
    set QUIET=
    set TESTCORE=1

    cd ..\netcoreapp2.1
    copy /y ..\net20\ironscheme.boot.dll .
    copy /y ..\net20\nunit.framework.dll .
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Conformance
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.SRFI
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Other

    cd %APPVEYOR_BUILD_FOLDER%
    call ci-artefact.cmd
artifacts:
- path: IronScheme-*.zip
- path: IronScheme*.*nupkg
before_deploy:
- cmd: |
    rem precompile libraries for Nuget
