version: 1.0.{build}
skip_tags: true
image: Visual Studio 2022
branches:
  only:
  - master
configuration: Release
assembly_info:
  patch: true
  file: IronScheme\IronScheme\Properties\AssemblyInfo.cs
  assembly_version: '1.0.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(SHA)'
install:
- cmd: |
    cd %APPVEYOR_BUILD_FOLDER%
    git submodule update --init --recursive
    set SHA=%APPVEYOR_REPO_COMMIT:~0,7%
    set QUIET=1
    choco install ilmerge
    set PATH=%PATH%;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\;%APPVEYOR_BUILD_FOLDER%\IronScheme\tools\;
    powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1'))) -Channel 9.0.1xx  -Quality daily -InstallDir 'c:\Program Files\dotnet'"
    for /d %%d in (%LOCALAPPDATA%\Microsoft\VisualStudio\17.0*) do echo UsePreviews=True > %%d\sdk.txt
nuget:
  project_feed: true
build_script:
- cmd: |
    rem dotnet restore "IronScheme\IronSchemeCore.sln"
    echo 1 > IronScheme\IronScheme\Compiler\numberlexer.lex.cs
    echo 1 > IronScheme\IronScheme\Compiler\ironscheme.lex.cs
    echo 1 > IronScheme\IronScheme\Compiler\NumberParser.y.cs
    echo 1 > IronScheme\IronScheme\Compiler\IronScheme.y.cs
    rem dotnet msbuild -restore "IronScheme\IronSchemeCore.sln" /v:m /logger:"C:\Program Files\AppVeyor\BuildAgent\dotnetcore\Appveyor.MSBuildLogger.dll" /p:Configuration=Release 
    msbuild -restore "IronScheme\IronSchemeCore.sln" /v:m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release 
test_script:
- cmd: |
    cd IronScheme\IronScheme.Console\bin\Release\net20
    echo (ironscheme-runtime) | IronScheme.Console.exe
    rem these have to be in order
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Bootstrap.Debug
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Compile.Debug
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Verify.Debug
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Bootstrap.Release
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Compile.Release
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Verify.Release
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Conformance
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.SRFI
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Other
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Teardown
    set QUIET=
    set TESTCORE=1

    cd ..\netcoreapp2.1
    copy /y ..\net20\ironscheme.boot.dll .
    copy /y ..\net20\nunit.framework.dll .
    echo (ironscheme-runtime) | dotnet IronScheme.ConsoleCore.dll
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Conformance
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.SRFI
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Other

    cd ..\net9.0
    copy /y ..\net20\ironscheme.boot.dll .
    copy /y ..\net20\nunit.framework.dll .
    echo (ironscheme-runtime) | IronScheme.ConsoleCore.exe
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Compile.Debug
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Verify.Debug
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Compile.Release
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Verify.Release
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Conformance
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.SRFI
    nunit-console IronScheme.Tests.dll /nologo /labels /run:IronScheme.Tests.Other

    cd %APPVEYOR_BUILD_FOLDER%
    call ci-artefact.cmd
artifacts:
- path: IronScheme-*.zip
- path: IronScheme*.*nupkg
before_deploy:
- cmd: |
    rem precompile libraries for Nuget
