version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
install:
- cmd: >-
    cinst ilmerge

    cinst zip

    curl -o xz.zip http://tukaani.org/xz/xz-5.2.1-windows.zip

    unzip -o xz.zip -d xz bin_i686-sse2/xz.exe

    copy xz\bin_i686-sse2\xz.exe "C:\Program Files\Git\usr\bin\"

    set PATH=%PATH%;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;
build_script:
- cmd: msbuild "IronScheme\IronSchemeCore.sln" /v:m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:TargetFrameworkVersion=v2.0 /p:Configuration=Release
test_script:
- cmd: >-
    cd IronScheme\IronScheme.Console\bin\Release

    rem these have to be in order

    nunit-console IronScheme.Tests.dll /run:IronScheme.Tests.Release /framework:net-2.0

    nunit-console IronScheme.Tests.dll /run:IronScheme.Tests.Debug /framework:net-2.0

    nunit-console IronScheme.Tests.dll /run:IronScheme.Tests.Setup /framework:net-2.0

    nunit-console IronScheme.Tests.dll /run:IronScheme.Tests.Conformance /framework:net-2.0

    nunit-console IronScheme.Tests.dll /run:IronScheme.Tests.SRFI /framework:net-2.0

    nunit-console IronScheme.Tests.dll /run:IronScheme.Tests.Other /framework:net-2.0

    nunit-console IronScheme.Tests.dll /run:IronScheme.Tests.Teardown /framework:net-2.0