version: 1.0.{build}
skip_tags: true
image: Visual Studio 2022
branches:
  only:
  - master
configuration: Release
assembly_info:
  patch: true
  file: IronScheme\IronScheme\Properties\AssemblyInfo.cs
  assembly_version: '1.0.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(SHA)'
install:
- cmd: |
    cd %APPVEYOR_BUILD_FOLDER%
    git submodule update --init --recursive
    set SHA=%APPVEYOR_REPO_COMMIT:~0,7%
    set QUIET=1
    set DOTNET_CLI_TELEMETRY_OPTOUT=1
    set DOTNET_NOLOGO=1
    rem for pevefiry and other build shit
    set PATH=%PATH%;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\;
    powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1'))) -Channel 9.0.1xx  -Quality daily -InstallDir 'c:\Program Files\dotnet'"
    for /d %%d in (%LOCALAPPDATA%\Microsoft\VisualStudio\17.0*) do echo UsePreviews=True > %%d\sdk.txt
    dotnet tool install --global dotnet-ilverify --prerelease
    dotnet tool install --global dotnet-ilrepack
nuget:
  project_feed: true
build_script:
- cmd: |
    dotnet restore "IronScheme.BuildTools\IronScheme.BuildTools.sln"
    dotnet restore "IronScheme\IronSchemeCore.sln"

    echo 1 > IronScheme\IronScheme\Compiler\numberlexer.lex.cs
    echo 1 > IronScheme\IronScheme\Compiler\ironscheme.lex.cs
    echo 1 > IronScheme\IronScheme\Compiler\NumberParser.y.cs
    echo 1 > IronScheme\IronScheme\Compiler\IronScheme.y.cs
    
    rem dotnet msbuild -restore "IronScheme\IronSchemeCore.sln" /v:m /logger:"C:\Program Files\AppVeyor\BuildAgent\dotnetcore\Appveyor.MSBuildLogger.dll" /p:Configuration=Release 
    msbuild -restore "IronScheme\IronSchemeCore.sln" /v:m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release /p:NoWarn="NETSDK1138;NU1702;NU1902;NU1903;NU1701;CS3021;SYSLIB0050"
test_script:
- cmd: |
    rem these have to be in order
    cd IronScheme\IronScheme.Console\bin\Release\net20
    echo (ironscheme-runtime) | IronScheme.Console32.exe
    nunit3-console --noh --noc --labels=BeforeAndAfter --noresult --stoponerror %TESTS% ..\..\..\..\IronScheme.Tests\bin\Release\IronScheme.Tests.dll

    set TESTCORE=1
    cd ..\net9.0
    copy /y ..\net20\ironscheme.boot.dll .
    echo (ironscheme-runtime) | IronScheme.ConsoleCore.exe
    nunit3-console --noh --noc --labels=BeforeAndAfter -noresult --stoponerror %TESTS% ..\..\..\..\IronScheme.Tests\bin\Release\IronScheme.Tests.dll

    cd ..\netcoreapp2.1
    copy /y ..\net20\ironscheme.boot.dll .
    echo (ironscheme-runtime) | dotnet IronScheme.ConsoleCore.dll
    set TESTS=--test=IronScheme.Tests.Conformance,IronScheme.Tests.SRFI,IronScheme.Tests.Other
    nunit3-console --noh --noc --labels=BeforeAndAfter --noresult --stoponerror %TESTS% ..\..\..\..\IronScheme.Tests\bin\Release\IronScheme.Tests.dll

    cd %APPVEYOR_BUILD_FOLDER%
    call ci-artefact.cmd
artifacts:
- path: IronScheme-*.zip
- path: IronScheme*.*nupkg
before_deploy:
- cmd: |
    rem precompile libraries for Nuget
