version: 1.1.{build}
skip_tags: true
image: Visual Studio 2022
branches:
  only:
  - master
  - beta
configuration: Release
assembly_info:
  patch: true
  file: IronScheme\IronScheme\Properties\AssemblyInfo.cs
  assembly_version: '1.0.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(SHA)'
install:
- cmd: |
    cd %APPVEYOR_BUILD_FOLDER%
    git submodule update --init --recursive
    set SHA=%APPVEYOR_REPO_COMMIT:~0,7%
    set QUIET=1
    set DOTNET_CLI_TELEMETRY_OPTOUT=1
    set DOTNET_NOLOGO=1
    rem for pevefiry and other build shit
    set PATH=%PATH%;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\;
    powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1'))) -Channel 9.0.1xx  -InstallDir 'c:\Program Files\dotnet'"
    for /d %%d in (%LOCALAPPDATA%\Microsoft\VisualStudio\17.0*) do echo UsePreviews=True > %%d\sdk.txt
    dotnet tool install --global dotnet-ilverify
    dotnet tool install --global dotnet-ilrepack
nuget:
  project_feed: true
build_script:
- cmd: |
    cd %APPVEYOR_BUILD_FOLDER%
    cd IronScheme
    call build.cmd
test_script:
- cmd: |
    cd %APPVEYOR_BUILD_FOLDER%
    cd IronScheme
    SET COMMON=--no-dependencies -tl:off -m -c Release IronScheme.Console/IronScheme.Console.csproj -f net9.0 -v:q -noWarn:CS1030,CS0162 -clp:NoSummary 
    rem dotnet build %COMMON% -r osx-x64
    rem dotnet build %COMMON% -r linux-x64
    call package.cmd
    call ci-artefact.cmd
artifacts:
- path: IronScheme-*.zip
- path: IronScheme*.*nupkg
before_deploy:
- cmd: |
    rem precompile libraries for Nuget

