;; Automatically generated by private/make-aliased-libraries.sps
#!r6rs
(library (srfi :25)
  (export
    array
    array-end
    array-rank
    array-ref
    array-set!
    array-start
    array?
    make-array
    shape
    share-array)
  (import (srfi :25 multi-dimensional-arrays))
)
