;; Automatically generated by private/make-aliased-libraries.sps
#!r6rs
(library (srfi :78)
  (export
    check
    check-ec
    check-passed?
    check-report
    check-reset!
    check-set-mode!)
  (import (srfi :78 lightweight-testing))
)
