IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\base.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\bytevectors.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\conditions.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\control.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\enums.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\eval.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\exceptions.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\hashtables.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\lists.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\mutable-pairs.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\mutable-strings.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\programs.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\r5rs.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\reader.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\sorting.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\syntax-case.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\unicode.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\arithmetic\bitwise.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\arithmetic\fixnums.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\arithmetic\flonums.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\io\ports.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\io\simple.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\records\procedural.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\records\syntactic.sps
IronSchemeConsole\bin\Debug\IronScheme.Console.exe tests\r6rs\run\leppie.sps
