name: IronScheme

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-2019]

    timeout-minutes: 10

    defaults:
      run:
        shell: ${{matrix.os == 'windows-2019' && cmd || bash}}
        working-directory: ./IronScheme

    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: 'recursive'
        fetch-depth: 0

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        dotnet-quality: 'daily'

    - name: Setup .NETCore 2.1
      if: ${{matrix.os == 'windows-2019'}}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 2.1.x

    - name: Build (sh)
      if: ${{matrix.os != 'windows-2019'}}
      run: sh build.sh

    - name: Build (cmd)
      if: ${{matrix.os == 'windows-2019'}}
      run: build.cmd

    - name: Test (sh)
      if: ${{matrix.os != 'windows-2019'}}
      run: sh test.sh

    - name: Test (cmd)
      if: ${{matrix.os == 'windows-2019'}}
      run: |
          test.cmd
          test.cmd /net9
          test.cmd /core

    - name: Package (sh)
      if: ${{matrix.os != 'windows-2019'}}
      run: sh package.sh

    - name: Package (sh)
      if: ${{matrix.os == 'windows-2019'}}
      run: package.cmd

    - name: Upload binlogs
      uses: actions/upload-artifact@v4
      with:
        name: binlog-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
        path: IronScheme/*.binlog
      if: ${{ always() }}

    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: packages-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
        path: IronScheme/bin/*.*
      if: ${{ always() }}
