name: IronScheme (Non-Windows)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
        working-directory: ./IronScheme
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: 'recursive'
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        dotnet-quality: 'daily'
    - name: Build
      run: sh build.sh
    - name: Test
      run: sh test.sh
    - name: Package
      run: sh package.sh
    - name: Upload binlogs
      uses: actions/upload-artifact@v4
      with:
        name: binlog-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
        path: ./*.binlog
      if: ${{ always() }}
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: packages-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
        path: ./bin/*.*
      if: ${{ always() }}
