name: IronScheme (OSX)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        dotnet-quality: 'daily'
    - name: Build
      run: cd IronScheme && sh build.sh
    - name: Test
      run: cd IronScheme && sh test.sh
    - name: Package
      run: cd IronScheme && sh package.sh
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: IronScheme/bin/*.*
