name: IronScheme (Windows)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          2.1.x
          9.0.x
        dotnet-quality: 'daily'
    - name: Build
      run: cd IronScheme && build.cmd
    - name: Test (.NET Framework)
      run: cd IronScheme && test.cmd
    - name: Test (.NET 9.0)
      run: cd IronScheme && test.cmd /net9
    - name: Test (.NET Core 2.1)
      run: cd IronScheme && test.cmd /core
    - name: Package
      run: cd IronScheme && package.cmd
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: packages-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
        path: IronScheme/bin/*.*
