# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: IronScheme (Windows)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2019
    defaults:
      run:
        shell: cmd

    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        dotnet-quality: 'daily'
    - name: Build
      run: cd IronScheme && build.cmd
    - name: Test
      run: cd IronScheme && test.cmd
    - name: Package
      run: cd IronScheme && package.cmd
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: zip
        path: IronScheme/bin/*.*
